import path from "node:path";
import fs from "node:fs/promises";
import { createReadStream } from "node:fs";
import ffmpeg from "fluent-ffmpeg";
import { supabase } from "../supabase.js";
import { logger } from "../logger.js";
import { buildKaraokeASS, buildHookASS } from "./captions.js";
import type { Moment } from "./score.js";
import type { Transcript } from "./transcribe.js";

type Args = {
  userId: string;
  jobId: string;
  sourcePath: string;
  index: number;
  moment: Moment;
  transcript: Transcript;
  niche: string;
  workDir: string;
  /** Free tier renders include the ClipForge watermark in the corner. */
  watermark?: boolean;
};

export type RenderResult = {
  storagePath: string;
  thumbnailPath: string;
  durationSec: number;
  /** Local path to the rendered MP4 (so a later step can build an AI thumbnail). */
  renderedFilePath: string;
};

export async function renderClip(a: Args): Promise<RenderResult> {
  const out = path.join(a.workDir, `clip-${a.index}.mp4`);
  const thumb = path.join(a.workDir, `clip-${a.index}.jpg`);
  const captionFile = path.join(a.workDir, `clip-${a.index}.ass`);
  const hookFile = path.join(a.workDir, `clip-${a.index}-hook.ass`);

  const duration = a.moment.end - a.moment.start;

  // 1) Generate ASS subtitles (karaoke word-by-word + hook overlay)
  await Promise.all([
    fs.writeFile(
      captionFile,
      buildKaraokeASS(a.transcript.words, a.niche, a.moment.start, a.moment.end),
    ),
    fs.writeFile(hookFile, buildHookASS(a.moment.hook ?? "", duration, a.niche)),
  ]);

  // 2) FFmpeg render: cut → scale → crop 9:16 → burn captions + hook → loudnorm
  const watermarkFilter = a.watermark
    ? `drawtext=fontfile=/usr/share/fonts/truetype/inter/Inter-Bold.ttf:` +
        `text='clipforge.bulsulabs.xyz':fontcolor=white@0.7:fontsize=28:` +
        `borderw=2:bordercolor=black@0.6:x=w-text_w-32:y=h-text_h-32`
    : null;

  await new Promise<void>((resolve, reject) => {
    ffmpeg(a.sourcePath)
      .setStartTime(a.moment.start)
      .duration(duration)
      .videoFilters([
        // upscale to fill 9:16 (1080x1920) without distortion
        "scale=-2:1920:force_original_aspect_ratio=increase",
        "crop=1080:1920",
        // burn karaoke captions (libass)
        `ass=${escapePath(captionFile)}`,
        // burn animated hook
        `ass=${escapePath(hookFile)}`,
        ...(watermarkFilter ? [watermarkFilter] : []),
      ])
      .audioFilters(["loudnorm=I=-16:LRA=11:TP=-1.5", "highpass=f=80", "lowpass=f=12000"])
      .outputOptions([
        "-c:v", "libx264",
        "-preset", "veryfast",
        "-crf", "20",
        "-c:a", "aac",
        "-b:a", "192k",
        "-ar", "44100",
        "-movflags", "+faststart",
        "-pix_fmt", "yuv420p",
        "-r", "30",
        "-profile:v", "high",
        "-level", "4.0",
      ])
      .on("start", (cmd) => logger.debug({ jobId: a.jobId, clip: a.index, cmd }, "ffmpeg start"))
      .on("stderr", (line) => {
        // surface ass errors so we know if fonts are missing
        if (line.includes("[Parsed_ass") && line.includes("font")) {
          logger.warn({ line }, "ass font notice");
        }
      })
      .on("end", () => resolve())
      .on("error", reject)
      .save(out);
  });

  // 3) Quick fallback thumbnail (peak frame). Real Mr.Beast-style thumb is generated by thumbnail.ts.
  await new Promise<void>((resolve, reject) => {
    ffmpeg(out)
      .seekInput(Math.min(0.4 + duration * 0.12, duration - 0.1))
      .frames(1)
      .size("540x960")
      .on("end", () => resolve())
      .on("error", reject)
      .save(thumb);
  });

  // 4) Upload both to Supabase Storage
  const storagePath = `${a.userId}/${a.jobId}/clip-${a.index}.mp4`;
  const thumbPath = `${a.userId}/${a.jobId}/clip-${a.index}.jpg`;

  const [vRes, tRes] = await Promise.all([
    supabase.storage.from("clipforge-videos-rendered").upload(storagePath, createReadStream(out) as any, {
      contentType: "video/mp4",
      upsert: true,
      duplex: "half",
    } as any),
    supabase.storage.from("clipforge-thumbnails").upload(thumbPath, createReadStream(thumb) as any, {
      contentType: "image/jpeg",
      upsert: true,
      duplex: "half",
    } as any),
  ]);
  if (vRes.error) throw vRes.error;
  if (tRes.error) throw tRes.error;

  await Promise.all([
    fs.unlink(thumb).catch(() => {}),
    fs.unlink(captionFile).catch(() => {}),
    fs.unlink(hookFile).catch(() => {}),
  ]);

  return { storagePath, thumbnailPath: thumbPath, durationSec: duration, renderedFilePath: out };
}

function escapePath(p: string) {
  // FFmpeg filter strings need colons escaped on the ass= filename
  return p.replace(/\\/g, "/").replace(/:/g, "\\:").replace(/'/g, "\\'");
}
